# Generated by Django 4.2.7 on 2026-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the user performing the transaction",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="Browser user agent for security tracking",
                null=True,
            ),
        ),
    ]
