# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("operations", "0002_alert"),
        ("operations", "0002_stocktransaction_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LOW_STOCK", "Low Stock Alert"),
                            ("OUT_OF_STOCK", "Out of Stock Alert"),
                            ("SYSTEM", "System Alert"),
                        ],
                        default="LOW_STOCK",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("quantity_at_alert", models.IntegerField(default=0)),
                ("threshold_at_alert", models.IntegerField(default=0)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="operations__is_reso_3110ff_idx",
                    ),
                    models.Index(
                        fields=["item", "is_resolved"],
                        name="operations__item_id_978b77_idx",
                    ),
                ],
            },
        ),
    ]
