# Generated by Django 4.2.7 on 2026-06-24 10:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                help_text="Optimized product image (max 500x500, WEBP)",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[500, 500],
                upload_to="products/",
            ),
        ),
    ]
